@startuml
note right of PaychecksController
  Bemærk: Controlleren anvender et data access layer til at
  kommunikere med databasen, men dette er blevet abstraheret væk
  i sekvensdiagrammet for at forbedre overskueligheden
end note

title GET /Paychecks - Sequence Diagram

participant "Frontend" as Frontend
participant "PaychecksController" as PaychecksController

participant "<<Database>>" as Database

activate Frontend
activate PaychecksController

Frontend -> PaychecksController: GET /paychecks\n{companyName, month}
PaychecksController -> PaychecksController: Validate request body
opt Invalid request body
    PaychecksController -> Frontend: 400 bad request
   
    deactivate Frontend
    return
end

PaychecksController -> Database: Query job by jobId and userId
activate Database
Database --> PaychecksController: job or null
deactivate Database
opt job not found
    PaychecksController -> Frontend: 404 not found
activate Frontend
   
    return
    deactivate Frontend
end

PaychecksController -> PaychecksController: CalculateSalaryBeforeTaxAndTotalHours(timeperiod, job)

PaychecksController -> Database: Query supplement details filtered by job
activate Database
Database --> PaychecksController: supplement details or null
deactivate Database

PaychecksController -> Database: Query workshifts filtered by timeperiod
activate Database
Database --> PaychecksController: workshifts or null
deactivate Database


loop for each workshift in workshifts
    PaychecksController -> PaychecksController: totalWorkedHours += workshift.EndTime - workshift.StartTime
    PaychecksController -> PaychecksController: totalSupplementPay += CalculateSupplementPayForWorkshift(workshift, supplementDetails)
end


PaychecksController -> Frontend: 200 OK, Paycheck
activate Frontend
deactivate Frontend

deactivate PaychecksController
deactivate Frontend

@enduml
