
@startuml

interface IWorkshiftService
{
AddWorkShift(WorkshiftDTO workshift): Task<WorkshiftDTO>
GetAllWorkShifts(): Task<List<WorkshiftDTO>>
}
class LogHoursPage
{ 
}

class LogHoursViewModel
{
 - IWorkshiftService workshiftService
 + DateTime selectedDate
 + TimeSpan startTime
 + TimeSpan endTime
 + EventCollection<Event> events
 + LogHoursViewModel(IWorkshiftService workshiftService)
 + InitializeCalendar(): Task
 + AddWorkShiftCommand: ICommand
}

class WorkshiftDTO
{
 + DateTime StartTime
 + DateTime EndTime
}

LogHoursViewModel --> IWorkshiftService

class WorkshiftService {
    - HttpClient _httpClient
    + WorkshiftService(HttpClient httpClient)
    + AddWorkShift(WorkshiftDTO workshift): Task<WorkshiftDTO> 
    + GetAllWorkShifts(): Task<List<WorkshiftDTO>> 
}


WorkshiftService --> WorkshiftDTO
IWorkshiftService --> WorkshiftDTO
LogHoursViewModel --> WorkshiftDTO
WorkshiftService ..|> IWorkshiftService

LogHoursPage --> LogHoursViewModel


@enduml