name: Build & Test (.NET)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # adjust if you're using .NET 7/6

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: code-coverage
          path: '**/TestResults/**/coverage.cobertura.xml'
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: '**/TestResults/**/coverage.cobertura.xml'

